
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
spring:
  application:
    name: service-user
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/huaqi?serverTimezone=Hongkong&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379

feign:
  hystrix:
    enabled: true


mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml
server:
  port: 8000

swagger:
  enable: true

security:
  oauth2:
    resource:
      id: user
      user-info-uri: http://localhost:8002/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:8002/oauth/token
      grant-type: client_credentials,password
      scope: server
