server:
  port: 8040

spring:
  application:
    name: microservice-gateway-zuul

zuul:
  routes:
    service-user: /userservice/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
